// Dummy blog posts data
export const dummyPosts = [
  {
    id: 1,
    title: "Getting Started with React Hooks: A Comprehensive Guide",
    body: "React Hooks have revolutionized the way we write React components. In this comprehensive guide, we'll explore useState, useEffect, and custom hooks to build powerful and maintainable applications. Learn how to manage state, handle side effects, and create reusable logic that will make your code cleaner and more efficient.",
    author: "Sarah Johnson",
    userId: 1,
    date: "2024-01-15T10:30:00.000Z",
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=500&fit=crop",
    readTime: 8,
  },
  {
    id: 2,
    title: "The Art of Minimalist Web Design",
    body: "Minimalism in web design is more than just a trend—it's a philosophy. Discover how to create stunning, user-friendly websites by embracing simplicity, white space, and purposeful design choices. We'll explore real-world examples and practical tips for implementing minimalist principles in your next project.",
    author: "Michael Chen",
    userId: 2,
    date: "2024-01-14T14:20:00.000Z",
    category: "Design",
    image:
      "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=500&fit=crop",
    readTime: 6,
  },
  {
    id: 3,
    title: "Building a Startup from Scratch: Lessons Learned",
    body: "Starting a business is an incredible journey filled with challenges and triumphs. In this post, I share my personal experience building a tech startup from the ground up, including the mistakes I made, the victories I celebrated, and the invaluable lessons learned along the way. Whether you're an aspiring entrepreneur or just curious about the startup world, this guide offers practical insights.",
    author: "Emily Rodriguez",
    userId: 3,
    date: "2024-01-13T09:15:00.000Z",
    category: "Business",
    image:
      "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=500&fit=crop",
    readTime: 10,
  },
  {
    id: 4,
    title: "10 Morning Habits That Will Transform Your Life",
    body: "Your morning routine sets the tone for your entire day. Discover ten powerful habits that successful people use to start their mornings with intention, energy, and focus. From meditation and exercise to journaling and mindful breakfast, these practices can help you become more productive, healthier, and happier.",
    author: "David Thompson",
    userId: 4,
    date: "2024-01-12T08:00:00.000Z",
    category: "Lifestyle",
    image:
      "https://images.unsplash.com/photo-1495364141860-b0d03eccd065?w=800&h=500&fit=crop",
    readTime: 5,
  },
  {
    id: 5,
    title: "Understanding JavaScript Closures and Scope",
    body: "Closures are one of the most powerful features in JavaScript, yet they often confuse developers. This deep dive explains how closures work, why they're useful, and how to leverage them in your code. We'll cover lexical scope, function factories, and practical examples that demonstrate the true power of closures in modern JavaScript development.",
    author: "Alex Martinez",
    userId: 5,
    date: "2024-01-11T16:45:00.000Z",
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800&h=500&fit=crop",
    readTime: 12,
  },
  {
    id: 6,
    title: "Color Theory for UI Designers: A Practical Approach",
    body: "Choosing the right colors for your user interface can make or break the user experience. Learn the fundamentals of color theory, including complementary colors, color psychology, and accessibility considerations. This guide provides actionable tips for creating beautiful, harmonious color schemes that resonate with your users.",
    author: "Jessica Lee",
    userId: 6,
    date: "2024-01-10T11:30:00.000Z",
    category: "Design",
    image:
      "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&h=500&fit=crop",
    readTime: 7,
  },
  {
    id: 7,
    title: "Scaling Your Business: When and How to Grow",
    body: "Growth is exciting, but scaling too quickly can be dangerous. This article explores the signs that your business is ready to scale, strategies for sustainable growth, and common pitfalls to avoid. Learn from real case studies of companies that scaled successfully and those that stumbled, so you can make informed decisions about your business's future.",
    author: "Robert Kim",
    userId: 7,
    date: "2024-01-09T13:20:00.000Z",
    category: "Business",
    image:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop",
    readTime: 9,
  },
  {
    id: 8,
    title: "The Ultimate Guide to Sustainable Living",
    body: "Living sustainably doesn't mean sacrificing comfort or convenience. Discover practical ways to reduce your environmental footprint through simple lifestyle changes. From reducing waste and conserving energy to choosing eco-friendly products and supporting local businesses, this guide shows you how to make a positive impact on the planet.",
    author: "Lisa Anderson",
    userId: 8,
    date: "2024-01-08T07:45:00.000Z",
    category: "Lifestyle",
    image:
      "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=500&fit=crop",
    readTime: 11,
  },
  {
    id: 9,
    title: "Mastering TypeScript: From Beginner to Advanced",
    body: "TypeScript has become the go-to language for building scalable JavaScript applications. This comprehensive tutorial takes you from basic types to advanced generics, decorators, and type guards. Whether you're new to TypeScript or looking to level up your skills, this guide provides clear explanations and practical examples.",
    author: "Chris Wong",
    userId: 9,
    date: "2024-01-07T15:10:00.000Z",
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&h=500&fit=crop",
    readTime: 15,
  },
  {
    id: 10,
    title: "Typography Best Practices for Modern Web Design",
    body: "Typography is the backbone of good design. Learn how to choose the right fonts, establish visual hierarchy, optimize readability, and create beautiful text layouts. This guide covers everything from font pairing and spacing to responsive typography and accessibility, helping you create websites that are both aesthetically pleasing and user-friendly.",
    author: "Amanda Foster",
    userId: 10,
    date: "2024-01-06T10:00:00.000Z",
    category: "Design",
    image:
      "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&h=500&fit=crop",
    readTime: 8,
  },
  {
    id: 11,
    title: "Financial Planning for Entrepreneurs",
    body: "Managing finances is crucial for any business owner. This guide covers budgeting, cash flow management, investment strategies, and tax planning specifically tailored for entrepreneurs. Learn how to separate personal and business finances, plan for growth, and build a solid financial foundation for your company's success.",
    author: "Thomas Baker",
    userId: 11,
    date: "2024-01-05T12:30:00.000Z",
    category: "Business",
    image:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=500&fit=crop",
    readTime: 10,
  },
  {
    id: 12,
    title: "Mindfulness and Meditation for Busy Professionals",
    body: "In our fast-paced world, taking time for mindfulness can seem impossible. This article shows busy professionals how to incorporate meditation and mindfulness practices into their daily routines. Discover quick techniques for stress reduction, improved focus, and better work-life balance that fit into even the busiest schedules.",
    author: "Karen Phillips",
    userId: 12,
    date: "2024-01-04T08:20:00.000Z",
    category: "Lifestyle",
    image:
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=500&fit=crop",
    readTime: 6,
  },
  {
    id: 13,
    title: "Building Progressive Web Apps with Service Workers",
    body: "Progressive Web Apps (PWAs) combine the best of web and mobile applications. Learn how to implement service workers, create offline experiences, and build apps that are fast, reliable, and engaging. This tutorial covers caching strategies, push notifications, and background sync to create truly progressive web experiences.",
    author: "Daniel Scott",
    userId: 13,
    date: "2024-01-03T14:40:00.000Z",
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=500&fit=crop",
    readTime: 13,
  },
  {
    id: 14,
    title: "UX Research Methods Every Designer Should Know",
    body: "Great design starts with understanding your users. Explore essential UX research methods including user interviews, surveys, usability testing, and analytics. Learn when to use each method, how to gather meaningful insights, and how to turn research findings into actionable design decisions that improve user experience.",
    author: "Sophie Turner",
    userId: 14,
    date: "2024-01-02T11:15:00.000Z",
    category: "Design",
    image:
      "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&h=500&fit=crop",
    readTime: 9,
  },
  {
    id: 15,
    title: "Remote Work: Building and Managing Distributed Teams",
    body: "The future of work is remote. Learn how to build, manage, and grow successful distributed teams. This comprehensive guide covers hiring remote talent, establishing communication protocols, fostering team culture, and maintaining productivity across time zones. Discover tools and strategies that make remote work work for everyone.",
    author: "James Wilson",
    userId: 15,
    date: "2024-01-01T09:30:00.000Z",
    category: "Business",
    image:
      "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=800&h=500&fit=crop",
    readTime: 11,
  },
];
